### PR TITLE
Added total marks

### PR DESCRIPTION
**Pull request by zivry**
Need to make sure TotalMarks can be int and not String.

### CODE REVIEW

**Comment by zivry** [comment]
Try with squashing!

**Comment by ezraroi** [comment]
You are missing the UserModel class update,  no?

**Comment by zivry** [comment]
working on it.

**Comment by zivry** [comment]
added, need to squash, my commit comments sucks

**Comment by ezraroi** [comment]
Done, thanks

**Comment by zivry** [comment]
Thank you!

**Pull request merged**
